### ISSUE TITLE
Setup HB_LOG_AND_DROP chain on start if it's missing

### ISSUE THREAD

**Issue by davemosk** [tower9/hostblock#2]
The following lines are in /etc/hostblock.conf:

## As example to automatically add HB_LOG_AND_DROP rules if host is restarted and rules are not restored with iptables-restore
iptables.rules.startup = -N HB_LOG_AND_DROP
iptables.rules.startup = -A HB_LOG_AND_DROP -j LOG --log-prefix "IPTABLES-DROPPED: " --log-level 4
iptables.rules.startup = -A HB_LOG_AND_DROP -j DROP

It would be good to implement this!

I have a workaround - I've put the following line into /lib/systemd/system/hostblock.service
ExecStartPre=/usr/local/bin/hostblock-init-iptables.sh

and /usr/local/bin/hostblock-init-iptables.sh is:
#!/bin/bash
#
# Initialise iptables for logging
#

cmd_result="$(iptables -S HB_LOG_AND_DROP 2<&1)"

if [[ $cmd_result =~ "iptables: No chain" ]]; then
  iptables -N HB_LOG_AND_DROP
  iptables -A HB_LOG_AND_DROP -j LOG --log-prefix "IPTABLES-DROPPED: " --log-level 4
  iptables -A HB_LOG_AND_DROP -j DROP
fi

... but it would be much cleaner to have this actually in the code.

BTW Thanks for writing this - it was just what I was looking for.

**Comment by tower9** [comment]
I wrote hostblock for myself to remember C++ and to play around with code (it was actually a re-write, originally it was in PHP). But I'm glad this works also for someone else except myself )) Feel free to throw issues here in github, will try to take a look at them once in a while.

I never stressed about this feature cause it is easy enough to solve it with other means, for example by using iptables-restore. Anyhow, can you check `issues/2` branch?
```
$ git checkout issues/2
$ make
$ sudo make install
```

Also note that I changed names of config parameters:
```
## iptables commands to execute during daemon startup
## If check does not return 0, then execute all add rules
## As example to automatically add HB_LOG_AND_DROP rules if host is restarted and rules are not restored with iptables-restore
iptables.startup.check = -S HB_LOG_AND_DROP
iptables.startup.add = -N HB_LOG_AND_DROP
iptables.startup.add = -A HB_LOG_AND_DROP -j LOG --log-prefix "IPTABLES-DROPPED: " --log-level 4
iptables.startup.add = -A HB_LOG_AND_DROP -j DROP
```

**Comment by tower9** [comment]
Merged, can use starting with v.1.0.4
