### ISSUE TITLE
Customise chain in block action

### ISSUE THREAD

**Issue by cyqsimon** [tower9/hostblock#3]
I already have a rule list in use in `iptables`, which looks something like this:
```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    x     x f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports xxxxx
    x     x DROP       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 /* Drop SSH Default Port Scan */
    x     x ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0            /* Allow All ICMP */
    x     x ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0            /* Allow All Loopback */
    x     x ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED /* Allow TCP E&R */
    x     x ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED /* Allow UDP E&R */
    x     x ACCEPT     tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:xxxxx state NEW /* Allow SSH */
    x     x Chain-1    all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            state NEW /* My Custom Chain 1 */
    x     x Chain-2    all  --  eth0   *       0.0.0.0/0            0.0.0.0/0            state NEW /* My Custom Chain 2 */
    x     x DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Drop all */
```

As you can see, it's a whitelist firewall - packets get dropped by default if no rule matches; and I like to keep my rules nicely managed in their own chains.

What I wanted to do is to create a "rule list chain" specifically for `hostblock`, and have all the rules automatically appended there. Something like this:
```
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    x     x f2b-sshd   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports xxxxx
    x     x HB-list    all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Block list for HostBlock */
    x     x DROP       tcp  --  eth0   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22 /* Drop SSH Default Port Scan */
  ...
    x     x DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Drop all */

Chain HB-list (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target           prot opt in     out     source               destination
    0     0 HB_LOG_AND_DROP  all  --  *      *       xxx.xxx.xxx.xxx      0.0.0.0/0
  ...

Chain HB_LOG_AND_DROP (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
  # Use default behaviour
```

<hr>

So I configured my `INPUT` chain and added `HB-list`, then configured `hostblock.conf` like this:
```
iptables.rules.block = --append HB-list --source %i --jump HB_LOG_AND_DROP
```

Unfortunately this did not work:
```
$ systemctl status hostblock
...
Address xxx.xxx.xxx.xxx is missing iptables rule, adding...
iptables v1.4.21: Cannot use -A with -A
Try `iptables -h' or 'iptables --help' for more information.
Failed to execute iptables, returned code: 512
Address xxx.xxx.xxx.xxx is missing iptables rule and failed to append rule to chain!
```

When I edited `iptables.rules.block` to use `-I --insert` instead of `-A`, `iptables` simply gave me a corresponding warning:
```
iptables v1.4.21: Cannot use -I with -A
```

So I assume what's happening is that `-A INPUT` is hard-coded, and any user attempt to configure the append target simply results in duplicating `-A` flags, which causes `iptables` to error. And this is a very great inconvenience.

I know I can work around it by setting my `INPUT` chain's policy to `DROP` and removing the last rule, but that causes clutter in my rules, and makes it more difficult for me to manage. I would like to avoid that if possible.

<hr>

Would it be possible for you to add a guard clause in code that checks for whether there are `-A` or `-I` in the user's configuration before applying the default `-A INPUT` flag?

Alternatively, perhaps you can add another configuration key, something like `iptables.rules.block_raw`? This way you can avoid introducing breaking changes.

Thanks in advance.

<hr>

Environment:

CentOS 7; Kernel 5.10.9; iptables 1.4.21; hostblock v.1.0.1 compiled w/ gcc 7.3.1

**Comment by tower9** [comment]
Sorry for being so late, failed to find time for this for far too long time.

Introduced new config option in [v.1.0.3](https://github.com/tower9/hostblock/releases/tag/v.1.0.3) which allows to specify whether to use -A or -I:
`## Whether to add iptables rule to the head or tail of the chain (default head)
#iptables.rules.pos = head`

`iptables.rules.block_raw` sounds like a good idea, will think about it.
