### ISSUE TITLE
blacklist limit 10000

### ISSUE THREAD

**Issue by ukrolelo** [tower9/hostblock#6]
For a while i have this in status
AbuseIPDB blacklist size: 10000
Why it is not taking new IPs? and increasing the ammount?
`curl -G https://api.abuseipdb.com/api/v2/blacklist \
    -d confidenceMinimum=75 \
    -d limit=9999999 \
    -H "Key: $YOUR_API_KEY" \
    -H "Accept: application/json"`
It is possible no?
When i read manual it says that non subscribe have a limit cap 10000.
So its basicaly taking everytime the same IPS right?

**Comment by tower9** [comment]
> So its basicaly taking everytime the same IPS right?

No, AbuseIPDB returns top most active ones (within a limit of max). If you run sync after 5min, then most likely nothing will change. Haven't checked recently, but if I remember correctly, some 30-50 % of blacklist changed if sync was ran after 24h.

`hostblock` does not know when AbuseIPDB no longer it considers as bad address - donno exact formulas they use, but it is report count and age based. There is also an option to request takedown from AbuseIPDB. I decided to simply keep this blacklist up to date with list what has been returned from AbuseIPDB - removing an address when it is no longer returned by AbuseIPDB `blacklist` endpoint.

AbuseIPDB API offers also `check` endpoint. I'm considering mby to implement a new feature where in hostblock config you could tell to not remove IPs from AbuseIPDB blacklist based on sync, but instead to re-check each new address after some interval using `check` endpoint and to remove only when check endpoint returns score under `abuseipdb.block.score`. Need to be careful with interval though - AbuseIPDB limits usage of that endpoint to 3000 requests / day. Not sure, but I'm afraid with re-check interval of couple of days, after a month there could be more than 3k addresses to re-check each day. This could also be combined with pattern matching to also check newly identified suspicious address for AbuseIPDB confidence score (also to re-check with the same interval). That might hit the 3k limit even sooner. And multiply it with number of hosts that run `hostblock` and use the same AbuseIPDB account.

Note, hostblock has local blacklist - it is not influenced by AbuseIPDB blacklist. Adding address there will basically work as a permanent ban until manually removed.

**Comment by ukrolelo** [comment]
That would be **awesome!!!** if you can manualy put check on the ip in the script. The limit is not a problem as in config maybe you could put some variable to set abuseipdb.maxdailycheck=3000 or rate like 2/m.

Or maybe would be easier just put the script on any drop but limit it with 3000 per 24hours.

I love that hostblock is holding the IP and extending the time if it DROP again :)))))))
I am planing to put a web server finaly,just waiting to gather some more bad IPs :>

**Comment by ukrolelo** [comment]
Web server up and running, its so awesome to see how everyone is going byebye :smile: hostblock is a lifesaver!!!!!!!!
`Total suspicious IP address count: 4427
AbuseIPDB blacklist size: 10000
Last AbuseIPDB blacklist sync time: 2021-06-04 22:18:45
AbuseIPDB blacklist generation time: 2021-06-04 22:18:44
Total suspicious activity: 13846
Total refused: 32346
Total whitelisted: 3
Total blacklisted: 0
Total blocked: 2946
`
